<?php
/**
 * @file
 * Code for the GSB Feature Diptych FPP feature.
 */

include_once 'gsb_feature_diptych_fpp.features.inc';

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_diptych_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['diptych'] = array(
    'label' => t('Diptych'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/diptych',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

  // Create diptych view_mode for responsive video.
  $entity_info['file']['view modes']['diptych'] = array(
    'label' => t('Diptych'),
    'custom settings' => TRUE,
  );
}
